name: Deploy to Caprover
permissions: read-all
on:
  # registry_package:
  #   types: [published]
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: ./
          files: ./
          outPath: deploy.tar

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: healthcheck
          token: "${{ secrets.CAPROVER_TOKEN }}"
          # image: ghcr.io/eddiehubcommunity/healthcheck:latest

  migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.4
      - name: install dependencies
        run: npm ci
      - name: run migrations
        run: npm run db:migrate:prod
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
